### PR TITLE
renamed timbradin:react-templates to timbradin-react-templates, and u…

### PR DESCRIPTION
**Pull request by janisskuja**
…pdated cosmos:browserify@0.7.0 to cosmos:browserify@0.7.3

### CODE REVIEW

**Comment by janisskuja** [comment]
I tried to launch spacedrop with "meteor" command in Windows 10 environment. 
At first, when cloning git repo I got this error:

Cloning into 'spacedrop'...
[...]
error: Invalid path 'packages/react-templates/.npm/plugin/timbrandin:react-templ
ates/.gitignore'
error: Invalid path 'packages/react-templates/.npm/plugin/timbrandin:react-templ
ates/README'
error: Invalid path 'packages/react-templates/.npm/plugin/timbrandin:react-templ
ates/npm-shrinkwrap.json'

Then when trying to launch it I got this error:

[...]
=> Started MongoDB.
timbrandin:react-templates: updating npm dependencies -- cheerio...

C:\Users\janis_000\AppData\Local.meteor\packages\meteor-tool\1.1.8\mt-os.window
s.x86_32\dev_bundle\lib\node_modules\fibers\future.js:245
                                                throw(ex);
                                                      ^
Error: ENOENT, mkdir 'D:\git\spacedrop\packages\react-templates.npm\plugin\timb
randin:react-templates-new-1yfw04k'
[...]

I fixed that by renaming timbradin:react-templates to timbradin-react-templates

after that I got this error:

D:\git\spacedrop>meteor
[[[[[ ~\D\git\spacedrop ]]]]]

=> Started proxy.
=> A patch (Meteor 1.2.0.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
=> Errors prevented startup:

   While processing files with cosmos:browserify (for target web.browser):
   packages/timbrandin-react-templates/client.browserify.js: Cannot find
   module 'classnames/dedupe' from
   'D:\git\spacedrop\packages\timbrandin-react-templates.npm\package'

=> Your application has errors. Waiting for file change.

I deleted .meteor/versions, launched project again, and it worked. Meteor had updated cosmos:browserify version to 0.7.3. so I left it, and changed everything else back.

Launched again.. and it seemed to fix the problem.

**Comment by timbrandin** [comment]
I don't think the package name change should make it any different though, I tried removing the .npm folder which meteor is fetching for us anyway if it is missing and added it to .gitignore, could you test that solution, if that doesn't make work, I'm all for changing the package name if it helps.

**Comment by janisskuja** [comment]
You might be right, it does not make a lot of sense that changing the name should have any impact. I usually don't use Windows machine to develop, just wanted to launch the project on home PC :) - maybe it's just a Windows thing.. I will test that solution later today when I am at home.

**Comment by timbrandin** [comment]
Cool, tell us how it goes! :+1:

**Comment by janisskuja** [comment]
I reverted commit and merged my fork to main project.. but still, this thing happens:

Error: ENOENT, mkdir 'D:\git\spacedrop\packages\react-templates.npm\plugin\timb
randin:react-templates-new-1wo2tws'

The thing is - Windows does not like the ":" character (at least according to this site: https://msdn.microsoft.com/en-us/library/aa365247#file_and_directory_names ) I am looking to fix the problem any other way than renaming plugin name (because it seems silly..), but can't find anything noteworthy.. 

If I think of something, I'll write here.

**Comment by timbrandin** [comment]
I know the reason now, it's because the build plugin for the .html.jsx
files had that name.

I've changed it now to just react-templates, which should be fine.

Thx for finding this issue. :)

2015-10-02 22:15 GMT+02:00 janisskuja notifications@github.com:

> I reverted commit and merged my fork to main project.. but still, this
> thing happens:
> 
> Error: ENOENT, mkdir
> 'D:\git\spacedrop\packages\react-templates.npm\plugin\timb
> randin:react-templates-new-1wo2tws'
> 
> The thing is - Windows does not like the ":" character (at least according
> to this site:
> https://msdn.microsoft.com/en-us/library/aa365247#file_and_directory_names
> ) I am looking to fix the problem any other way than renaming plugin name
> (because it seems silly..), but can't find anything noteworthy..
> 
> If I think of something, I'll write here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/spacedrop/spacedrop/pull/10#issuecomment-145143870.

## 

Cheers,
// Tim Brandin @timbrandin https://twitter.com/#!/timbrandin
http://timbrandin.com
http://studiointeract.com

**Comment by timbrandin** [comment]
Did you have a chance to check this out?

**Pull request closed without merging**
