### PR TITLE
Review + some additional features

### PR DESCRIPTION
**Pull request by PEM--**
Now, we have a lot on our hands :wink:.

### CODE REVIEW

**Comment by timbrandin** [comment]
LGTM haha, prefect! Btw, what's your Slack nickname so that I can add you to the management group!?

**Comment by PEM--** [comment]
@pem

**Comment by PEM--** [comment]
Or you can shoot me emails. It's public info on my Github page :wink:

**Comment by timbrandin** [comment]
I'm not sure you're on Slack then. I'll send an invite.

**Pull request merged**
